/**
 *
 * @author jotaele
 */
package GUI;

import java.util.ArrayList;
import napakalaki.BadConsequence;
import napakalaki.TreasureKind;


public class BadConsequenceView extends javax.swing.JPanel {

    
    public BadConsequence badConsequenceModel;
    
    private String KindsToString(ArrayList<TreasureKind> a) {
        
        String out = " ";
        
        for (TreasureKind kind : a) {
            out += kind.toString();
            out += " ";
        }
        
        return out;
    }
    
    void setBadConsequence(BadConsequence bc) {
        
        badConsequenceModel = bc;
        
        LText.setText(badConsequenceModel.getText());
        //LNiveles.setText(Integer.toString(badConsequenceModel.getLevels()));
        //Lnvisibles.setText(Integer.toString(badConsequenceModel.getnVisible()));
        //Lnocultos.setText(Integer.toString(badConsequenceModel.getnHidden()));
        //LDeath.setText(Boolean.toString(badConsequenceModel.getDeath()));
        //LVisibleKind.setText( KindsToString( badConsequenceModel.getSpecificVisibleTreasures() ) );
        //LOcultoKind.setText( KindsToString( badConsequenceModel.getSpecificVisibleTreasures() ) );
        
        repaint();
    }
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LText = new javax.swing.JLabel();

        setLayout(null);

        LText.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        LText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LText.setText("Texto Mal Rollo");
        add(LText);
        LText.setBounds(10, 30, 440, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LText;
    // End of variables declaration//GEN-END:variables
}
