/**
 *
 * @author jotaele
 */

package GUI;

import napakalaki.Monster;



public class MonsterView extends javax.swing.JPanel {

    Monster monsterModel;
    
    void setMonster(Monster m) {
        
        monsterModel = m;
        
        LName.setText(monsterModel.getName());
        LCombatLevel.setText( Integer.toString(monsterModel.getCombatLevel()) );
        prizeView.setPrize(monsterModel.getPrize());
        badConsequenceView.setBadConsequence(monsterModel.getBadConsequence());
       
        
        if (monsterModel.getLevelChangeAgainstCultistPlayer() != 0) { // Si el monstruo tiene incremento para Sectarios...
            
            NumSpecialCultist.setVisible(true); // ...Lo mostramos
            LCultistText.setVisible(true);
            
            if (monsterModel.getLevelChangeAgainstCultistPlayer() > 0) {
                NumSpecialCultist.setText("+"+Integer.toString(monsterModel.getLevelChangeAgainstCultistPlayer()));
            } else {
                NumSpecialCultist.setText(Integer.toString(monsterModel.getLevelChangeAgainstCultistPlayer()));
            }
            
        } else { // Si no tiene...
            NumSpecialCultist.setVisible(false); //...Lo ocultamos
            LCultistText.setVisible(false);
        }
        
        
        repaint();
    }
    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LName = new javax.swing.JLabel();
        LCombatLevel = new javax.swing.JLabel();
        prizeView = new GUI.PrizeView();
        badConsequenceView = new GUI.BadConsequenceView();
        jSeparator1 = new javax.swing.JSeparator();
        LevelNameL = new javax.swing.JLabel();
        NumSpecialCultist = new javax.swing.JLabel();
        LCultistText = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(550, 500));
        setLayout(null);

        LName.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LName.setText("Nombre Monstruo");
        add(LName);
        LName.setBounds(20, 40, 470, 40);

        LCombatLevel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        LCombatLevel.setText("0");
        add(LCombatLevel);
        LCombatLevel.setBounds(260, 110, 230, 29);

        prizeView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buen Rollo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 12))); // NOI18N
        add(prizeView);
        prizeView.setBounds(20, 340, 470, 100);

        badConsequenceView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mal Rollo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 12))); // NOI18N
        add(badConsequenceView);
        badConsequenceView.setBounds(20, 450, 470, 70);
        add(jSeparator1);
        jSeparator1.setBounds(20, 90, 470, 10);

        LevelNameL.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        LevelNameL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LevelNameL.setText("Nivel:");
        LevelNameL.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(LevelNameL);
        LevelNameL.setBounds(20, 120, 220, 20);

        NumSpecialCultist.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        NumSpecialCultist.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NumSpecialCultist.setText("+ 0");
        add(NumSpecialCultist);
        NumSpecialCultist.setBounds(25, 150, 200, 20);

        LCultistText.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        LCultistText.setText("contra sectarios");
        add(LCultistText);
        LCultistText.setBounds(230, 150, 260, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCombatLevel;
    private javax.swing.JLabel LCultistText;
    private javax.swing.JLabel LName;
    private javax.swing.JLabel LevelNameL;
    private javax.swing.JLabel NumSpecialCultist;
    private GUI.BadConsequenceView badConsequenceView;
    private javax.swing.JSeparator jSeparator1;
    private GUI.PrizeView prizeView;
    // End of variables declaration//GEN-END:variables
}
