
/**
 *
 * @author jotaele
 */

package GUI;

import napakalaki.Prize;


public class PrizeView extends javax.swing.JPanel {

    
    public Prize prizeModel;
    
    void setPrize(Prize pr) {
        
        prizeModel = pr;
        
        LNiveles.setText(Integer.toString(prizeModel.getLevels()));
        LTesoros.setText(Integer.toString(prizeModel.getTreasures()));
        
        repaint(); //Para actualizar el texto de las etiquetas alteradas
    }
    
    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTesoros = new javax.swing.JLabel();
        LNiveles = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        LTesoros.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        LTesoros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTesoros.setText("0");
        add(LTesoros);
        LTesoros.setBounds(50, 50, 160, 25);

        LNiveles.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        LNiveles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LNiveles.setText("0");
        add(LNiveles);
        LNiveles.setBounds(280, 50, 160, 25);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("Número de Tesoros Ganados");
        add(jLabel1);
        jLabel1.setBounds(50, 30, 170, 15);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel2.setText("Número de Niveles Ganados");
        add(jLabel2);
        jLabel2.setBounds(280, 30, 160, 15);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LNiveles;
    private javax.swing.JLabel LTesoros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
