/**
 *
 * @author jotaelediaz
 */
package GUI;

import napakalaki.Treasure;
import napakalaki.TreasureKind;


public class TreasureView extends javax.swing.JPanel {

    Treasure treasureModel;
    private boolean selected = false;
    
    public boolean isSelected() {
        return selected;
    }
    
    public Treasure getTreasure() {
        return treasureModel;
    }
    
    //Método que define el objeto de tipo Tesoro que se mostrará en la vista
    public void setTreasure (Treasure t) {
        
        treasureModel = t;
        
        name.setText( (treasureModel.getName()) );
        maxbonus.setText( Integer.toString(treasureModel.getMaxBonus())  );
        minbonus.setText( Integer.toString(treasureModel.getMinBonus()) );
        coins.setText( Integer.toString(treasureModel.getGoldCoins()) );
        
        TreasureKind thiskind = treasureModel.getKind(); 
        switch (thiskind) {            
            case armor: kind.setText("Armadura"); break;        
            case oneHand: kind.setText("Una mano"); break;      
            case bothHand: kind.setText("Dos manos"); break;            
            case helmet: kind.setText("Casco"); break;            
            case shoe: kind.setText("Calzado"); break;            
            case necklace: kind.setText("Collar"); break;    
        }
        

        repaint(); //Para que se reimprima el formulario con el tesoro.
        
    }
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        minbonus = new javax.swing.JLabel();
        coins = new javax.swing.JLabel();
        kind = new javax.swing.JLabel();
        maxbonus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextGoldL = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(218, 218, 218));
        setMaximumSize(new java.awt.Dimension(260, 132));
        setMinimumSize(new java.awt.Dimension(260, 132));
        setPreferredSize(new java.awt.Dimension(260, 132));
        setSize(new java.awt.Dimension(260, 132));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        name.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("name");
        add(name);
        name.setBounds(20, 10, 230, 14);

        minbonus.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        minbonus.setText("0");
        add(minbonus);
        minbonus.setBounds(130, 40, 18, 20);

        coins.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        coins.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        coins.setText("0");
        add(coins);
        coins.setBounds(11, 100, 110, 30);

        kind.setFont(new java.awt.Font("Ubuntu", 2, 11)); // NOI18N
        kind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kind.setText("kind");
        add(kind);
        kind.setBounds(10, 70, 250, 14);

        maxbonus.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        maxbonus.setText("0");
        add(maxbonus);
        maxbonus.setBounds(170, 40, 20, 20);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1);
        jSeparator1.setBounds(10, 30, 250, 10);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Bonus:");
        add(jLabel1);
        jLabel1.setBounds(80, 40, 40, 20);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("/");
        add(jLabel2);
        jLabel2.setBounds(150, 40, 7, 21);

        TextGoldL.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        TextGoldL.setText(" Piezas de oro");
        add(TextGoldL);
        TextGoldL.setBounds(126, 100, 130, 30);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator2);
        jSeparator2.setBounds(10, 90, 250, 10);
    }// </editor-fold>//GEN-END:initComponents

    //Función que selecciona tesoros al hacer click sobre ellos (Cambia el color para indicarlo)
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        if ( isSelected() ) {
            
            selected = false;
            setBackground(new java.awt.Color(218, 218, 218));
            repaint();
            
        } else {
            
            selected = true;
            setBackground(new java.awt.Color(102, 102, 102));
            repaint();
        }
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextGoldL;
    private javax.swing.JLabel coins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel kind;
    private javax.swing.JLabel maxbonus;
    private javax.swing.JLabel minbonus;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
